server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nashdaD105@gmail.com
    password: ckrjouepglanjbcx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  redis:
    host: j9d105.p.ssafy.io
    port: 6379
  session:
    timeout: 600
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on-save

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  datasource:
#    url: jdbc:h2:tcp://localhost/~/nashda
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
      
      #MySQL
      url: jdbc:mysql://j9d105.p.ssafy.io:3306/D105?serverTimezone=UTC&characterEncoding=UTF-8
      username: nash
      password: d105nashda
      driver-class-name: com.mysql.cj.jdbc.Driver

  #    hikari:
  #      maximum-pool-size:1
  main:
    allow-circular-references: true

  profiles:
    include: db

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       show_sql: true
      # format_sql: true



jwt:
  issuer: thisiseunjin@nashda.com
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

logging:
  level:
    org:
    # hibernate:
    #   type:
    #     descriptor:
    #       sql: debug




cloud:
  aws:
    s3:
      bucket: nashda
    credentials:
      access-key: AKIAZCTY5UQEI3PX5TF5
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false