server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nashdaD105@gmail.com
    password: ckrjouepglanjbcx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  redis:
    host: j9d105.p.ssafy.io
    port: 6379
  session:
    timeout: 600
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on-save
  data:
    mongodb:
      uri: mongodb://nash:d105nashda@j9d105.p.ssafy.io:27017/nashda?authSource=admin&authMechanism=SCRAM-SHA-1

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  datasource:
    url: jdbc:h2:tcp://localhost/~/nashda
    username: sa
    password:
    driver-class-name: org.h2.Driver

  main:
    allow-circular-references: true

  profiles:
    include: db

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      # show_sql: true
      # format_sql: true



jwt:
  issuer: thisiseunjin@nashda.com
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

logging:
  level:
    org:
    # hibernate:
    #   type:
    #     descriptor:
    #       sql: debug
