server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  redis:
    host: localhost
    port: 6379
  session :
    timeout : 600
    store-type: redis
    redis :
      namespace: spring:session
      flush-mode: on-save

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  datasource:
    #        MySQL ??
    #        url: jdbc:mysql://j9d105.p.ssafy.io:3306/D105?serverTimezone=UTC&characterEncoding=UTF-8
    #        username: nash
    #        password: d105nashda
    #        driver-class-name: com.mysql.cj.jdbc.Driver


    #   H2 ??
    url:  jdbc:h2:tcp://localhost/~/nashda
    username: sa
    password:
    driver-class-name: org.h2.Driver

  #    hikari:
  #      maximum-pool-size:1
  main:
    allow-circular-references: true

  profiles:
    include: db

  jpa:
    hibernate:
      ddl-auto: create #create update none
    # show-sql: true
    properties:
      hibernate:
      #        show_sql: true
      # format_sql: true



logging:
  level:
    org:
    # hibernate:
    #   type:
    #     descriptor:
    #       sql: debug
