server:
  port: 8082
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  data:
    mongodb:
      uri: mongodb://nash:d105nashda@j9d105.p.ssafy.io:27017/nashda?authSource=admin&authMechanism=SCRAM-SHA-1
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

logging:
  level:
    org:
