# 나의 python 버전
FROM python:3.10.11

# /code 폴더 만들기
WORKDIR /code

# ./requirements.txt 를 /code/requirements.txt 로 복사
COPY ./requirements.txt /code/requirements.txt

RUN pip install --upgrade --no-deps --force-reinstall -r requirements.txt
RUN apt-get update
RUN apt-get install libasound-dev libportaudio2 libportaudiocpp0 portaudio19-dev -y
RUN apt install ffmpeg -y
RUN pip install pyaudio
RUN pip3 install "transformers[torch]"

# requirements.txt 를 보고 모듈 전체 설치(-r)
#RUN pip install -r requirements.txt

# 이제 app 에 있는 파일들을 /code/app 에 복사
COPY ./app /code/app

# 실행
CMD uvicorn app.main:app --port 8083 --host 0.0.0.0

